// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: latest/test-lagi.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestServiceLagiClient is the client API for TestServiceLagi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceLagiClient interface {
	TestServiceWithParam(ctx context.Context, in *TestRequestLagi, opts ...grpc.CallOption) (*TestResponseLagi, error)
}

type testServiceLagiClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceLagiClient(cc grpc.ClientConnInterface) TestServiceLagiClient {
	return &testServiceLagiClient{cc}
}

func (c *testServiceLagiClient) TestServiceWithParam(ctx context.Context, in *TestRequestLagi, opts ...grpc.CallOption) (*TestResponseLagi, error) {
	out := new(TestResponseLagi)
	err := c.cc.Invoke(ctx, "/proto.TestServiceLagi/TestServiceWithParam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServiceLagiServer is the server API for TestServiceLagi service.
// All implementations should embed UnimplementedTestServiceLagiServer
// for forward compatibility
type TestServiceLagiServer interface {
	TestServiceWithParam(context.Context, *TestRequestLagi) (*TestResponseLagi, error)
}

// UnimplementedTestServiceLagiServer should be embedded to have forward compatible implementations.
type UnimplementedTestServiceLagiServer struct {
}

func (UnimplementedTestServiceLagiServer) TestServiceWithParam(context.Context, *TestRequestLagi) (*TestResponseLagi, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TestServiceWithParam not implemented")
}

// UnsafeTestServiceLagiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceLagiServer will
// result in compilation errors.
type UnsafeTestServiceLagiServer interface {
	mustEmbedUnimplementedTestServiceLagiServer()
}

func RegisterTestServiceLagiServer(s grpc.ServiceRegistrar, srv TestServiceLagiServer) {
	s.RegisterService(&TestServiceLagi_ServiceDesc, srv)
}

func _TestServiceLagi_TestServiceWithParam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequestLagi)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceLagiServer).TestServiceWithParam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.TestServiceLagi/TestServiceWithParam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceLagiServer).TestServiceWithParam(ctx, req.(*TestRequestLagi))
	}
	return interceptor(ctx, in, info, handler)
}

// TestServiceLagi_ServiceDesc is the grpc.ServiceDesc for TestServiceLagi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestServiceLagi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TestServiceLagi",
	HandlerType: (*TestServiceLagiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TestServiceWithParam",
			Handler:    _TestServiceLagi_TestServiceWithParam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "latest/test-lagi.proto",
}
